version: "3.8"

services:
  app:
    image: starksim/drive_backend
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/avalon_backend/config.yaml
    container_name: "avalon_backend"
    networks:
      default:
        - aliases:
            - avalon_backend

networks:
  default:
    name: graphql_federation
    external: true