// Code generated by ent, DO NOT EDIT.

package ent

import (
	"avalon_backend/pkg/ent/card"
	"avalon_backend/pkg/ent/room"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int64 `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// CardEdge is the edge representation of Card.
type CardEdge struct {
	Node   *Card  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// CardConnection is the connection containing edges to Card.
type CardConnection struct {
	Edges      []*CardEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *CardConnection) build(nodes []*Card, pager *cardPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Card
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Card {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Card {
			return nodes[i]
		}
	}
	c.Edges = make([]*CardEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &CardEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// CardPaginateOption enables pagination customization.
type CardPaginateOption func(*cardPager) error

// WithCardOrder configures pagination ordering.
func WithCardOrder(order *CardOrder) CardPaginateOption {
	if order == nil {
		order = DefaultCardOrder
	}
	o := *order
	return func(pager *cardPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultCardOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithCardFilter configures pagination filter.
func WithCardFilter(filter func(*CardQuery) (*CardQuery, error)) CardPaginateOption {
	return func(pager *cardPager) error {
		if filter == nil {
			return errors.New("CardQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type cardPager struct {
	order  *CardOrder
	filter func(*CardQuery) (*CardQuery, error)
}

func newCardPager(opts []CardPaginateOption) (*cardPager, error) {
	pager := &cardPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultCardOrder
	}
	return pager, nil
}

func (p *cardPager) applyFilter(query *CardQuery) (*CardQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *cardPager) toCursor(c *Card) Cursor {
	return p.order.Field.toCursor(c)
}

func (p *cardPager) applyCursors(query *CardQuery, after, before *Cursor) *CardQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultCardOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *cardPager) applyOrder(query *CardQuery, reverse bool) *CardQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultCardOrder.Field {
		query = query.Order(direction.orderFunc(DefaultCardOrder.Field.field))
	}
	return query
}

func (p *cardPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultCardOrder.Field {
			b.Comma().Ident(DefaultCardOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Card.
func (c *CardQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...CardPaginateOption,
) (*CardConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newCardPager(opts)
	if err != nil {
		return nil, err
	}
	if c, err = pager.applyFilter(c); err != nil {
		return nil, err
	}
	conn := &CardConnection{Edges: []*CardEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = c.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	c = pager.applyCursors(c, after, before)
	c = pager.applyOrder(c, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		c.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := c.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := c.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// CardOrderFieldCreatedAt orders Card by created_at.
	CardOrderFieldCreatedAt = &CardOrderField{
		field: card.FieldCreatedAt,
		toCursor: func(c *Card) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.CreatedAt,
			}
		},
	}
	// CardOrderFieldUpdatedAt orders Card by updated_at.
	CardOrderFieldUpdatedAt = &CardOrderField{
		field: card.FieldUpdatedAt,
		toCursor: func(c *Card) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.UpdatedAt,
			}
		},
	}
	// CardOrderFieldDeletedAt orders Card by deleted_at.
	CardOrderFieldDeletedAt = &CardOrderField{
		field: card.FieldDeletedAt,
		toCursor: func(c *Card) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.DeletedAt,
			}
		},
	}
	// CardOrderFieldName orders Card by name.
	CardOrderFieldName = &CardOrderField{
		field: card.FieldName,
		toCursor: func(c *Card) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.Name,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f CardOrderField) String() string {
	var str string
	switch f.field {
	case card.FieldCreatedAt:
		str = "CREATED_AT"
	case card.FieldUpdatedAt:
		str = "UPDATED_AT"
	case card.FieldDeletedAt:
		str = "DELETED_AT"
	case card.FieldName:
		str = "NAME"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f CardOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *CardOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("CardOrderField %T must be a string", v)
	}
	switch str {
	case "CREATED_AT":
		*f = *CardOrderFieldCreatedAt
	case "UPDATED_AT":
		*f = *CardOrderFieldUpdatedAt
	case "DELETED_AT":
		*f = *CardOrderFieldDeletedAt
	case "NAME":
		*f = *CardOrderFieldName
	default:
		return fmt.Errorf("%s is not a valid CardOrderField", str)
	}
	return nil
}

// CardOrderField defines the ordering field of Card.
type CardOrderField struct {
	field    string
	toCursor func(*Card) Cursor
}

// CardOrder defines the ordering of Card.
type CardOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *CardOrderField `json:"field"`
}

// DefaultCardOrder is the default ordering of Card.
var DefaultCardOrder = &CardOrder{
	Direction: OrderDirectionAsc,
	Field: &CardOrderField{
		field: card.FieldID,
		toCursor: func(c *Card) Cursor {
			return Cursor{ID: c.ID}
		},
	},
}

// ToEdge converts Card into CardEdge.
func (c *Card) ToEdge(order *CardOrder) *CardEdge {
	if order == nil {
		order = DefaultCardOrder
	}
	return &CardEdge{
		Node:   c,
		Cursor: order.Field.toCursor(c),
	}
}

// RoomEdge is the edge representation of Room.
type RoomEdge struct {
	Node   *Room  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// RoomConnection is the connection containing edges to Room.
type RoomConnection struct {
	Edges      []*RoomEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *RoomConnection) build(nodes []*Room, pager *roomPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Room
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Room {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Room {
			return nodes[i]
		}
	}
	c.Edges = make([]*RoomEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &RoomEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// RoomPaginateOption enables pagination customization.
type RoomPaginateOption func(*roomPager) error

// WithRoomOrder configures pagination ordering.
func WithRoomOrder(order *RoomOrder) RoomPaginateOption {
	if order == nil {
		order = DefaultRoomOrder
	}
	o := *order
	return func(pager *roomPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultRoomOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithRoomFilter configures pagination filter.
func WithRoomFilter(filter func(*RoomQuery) (*RoomQuery, error)) RoomPaginateOption {
	return func(pager *roomPager) error {
		if filter == nil {
			return errors.New("RoomQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type roomPager struct {
	order  *RoomOrder
	filter func(*RoomQuery) (*RoomQuery, error)
}

func newRoomPager(opts []RoomPaginateOption) (*roomPager, error) {
	pager := &roomPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultRoomOrder
	}
	return pager, nil
}

func (p *roomPager) applyFilter(query *RoomQuery) (*RoomQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *roomPager) toCursor(r *Room) Cursor {
	return p.order.Field.toCursor(r)
}

func (p *roomPager) applyCursors(query *RoomQuery, after, before *Cursor) *RoomQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultRoomOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *roomPager) applyOrder(query *RoomQuery, reverse bool) *RoomQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultRoomOrder.Field {
		query = query.Order(direction.orderFunc(DefaultRoomOrder.Field.field))
	}
	return query
}

func (p *roomPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultRoomOrder.Field {
			b.Comma().Ident(DefaultRoomOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Room.
func (r *RoomQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...RoomPaginateOption,
) (*RoomConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newRoomPager(opts)
	if err != nil {
		return nil, err
	}
	if r, err = pager.applyFilter(r); err != nil {
		return nil, err
	}
	conn := &RoomConnection{Edges: []*RoomEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = r.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	r = pager.applyCursors(r, after, before)
	r = pager.applyOrder(r, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		r.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := r.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := r.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// RoomOrderFieldCreatedAt orders Room by created_at.
	RoomOrderFieldCreatedAt = &RoomOrderField{
		field: room.FieldCreatedAt,
		toCursor: func(r *Room) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.CreatedAt,
			}
		},
	}
	// RoomOrderFieldUpdatedAt orders Room by updated_at.
	RoomOrderFieldUpdatedAt = &RoomOrderField{
		field: room.FieldUpdatedAt,
		toCursor: func(r *Room) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.UpdatedAt,
			}
		},
	}
	// RoomOrderFieldDeletedAt orders Room by deleted_at.
	RoomOrderFieldDeletedAt = &RoomOrderField{
		field: room.FieldDeletedAt,
		toCursor: func(r *Room) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.DeletedAt,
			}
		},
	}
	// RoomOrderFieldName orders Room by name.
	RoomOrderFieldName = &RoomOrderField{
		field: room.FieldName,
		toCursor: func(r *Room) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.Name,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f RoomOrderField) String() string {
	var str string
	switch f.field {
	case room.FieldCreatedAt:
		str = "CREATED_AT"
	case room.FieldUpdatedAt:
		str = "UPDATED_AT"
	case room.FieldDeletedAt:
		str = "DELETED_AT"
	case room.FieldName:
		str = "NAME"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f RoomOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *RoomOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("RoomOrderField %T must be a string", v)
	}
	switch str {
	case "CREATED_AT":
		*f = *RoomOrderFieldCreatedAt
	case "UPDATED_AT":
		*f = *RoomOrderFieldUpdatedAt
	case "DELETED_AT":
		*f = *RoomOrderFieldDeletedAt
	case "NAME":
		*f = *RoomOrderFieldName
	default:
		return fmt.Errorf("%s is not a valid RoomOrderField", str)
	}
	return nil
}

// RoomOrderField defines the ordering field of Room.
type RoomOrderField struct {
	field    string
	toCursor func(*Room) Cursor
}

// RoomOrder defines the ordering of Room.
type RoomOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *RoomOrderField `json:"field"`
}

// DefaultRoomOrder is the default ordering of Room.
var DefaultRoomOrder = &RoomOrder{
	Direction: OrderDirectionAsc,
	Field: &RoomOrderField{
		field: room.FieldID,
		toCursor: func(r *Room) Cursor {
			return Cursor{ID: r.ID}
		},
	},
}

// ToEdge converts Room into RoomEdge.
func (r *Room) ToEdge(order *RoomOrder) *RoomEdge {
	if order == nil {
		order = DefaultRoomOrder
	}
	return &RoomEdge{
		Node:   r,
		Cursor: order.Field.toCursor(r),
	}
}
